##位姿变换

In [1]:
import roboticstoolbox as rtb
from spatialmath import *
import numpy as np
%matplotlib tk

SE 平移旋转一起

In [2]:
T=SE2(1, 2, np.pi/3)

In [3]:
T

   0.5      -0.866     1         
   0.866     0.5       2         
   0         0         1         


In [4]:
help(SE2)

Help on class SE2 in module spatialmath.pose2d:

class SE2(SO2)
 |  SE2(x=None, y=None, theta=None, *, unit='rad', check=True)
 |  
 |     SE(2) matrix class
 |  
 |     This subclass represents rigid-body motion (pose) in 2D space.  Internally
 |     it is a 3x3 homogeneous transformation matrix belonging to the group SE(2).
 |  
 |  .. inheritance-diagram:: spatialmath.pose2d.SE2
 |     :top-classes: collections.UserList
 |     :parts: 1
 |  
 |  Method resolution order:
 |      SE2
 |      SO2
 |      spatialmath.baseposematrix.BasePoseMatrix
 |      spatialmath.baseposelist.BasePoseList
 |      collections.UserList
 |      collections.abc.MutableSequence
 |      collections.abc.Sequence
 |      collections.abc.Reversible
 |      collections.abc.Collection
 |      collections.abc.Sized
 |      collections.abc.Iterable
 |      collections.abc.Container
 |      abc.ABC
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  SE3(self, z=0)
 |      Create SE(3) from SE(2)
 |    

In [4]:
T=SE2(1, 2, 60, unit='deg')
T

   0.5      -0.866     1         
   0.866     0.5       2         
   0         0         1         


In [6]:
initial_point=np.array([[0],[0],[1]])

In [7]:
initial_point

array([[0],
       [0],
       [1]])

In [8]:
initial_point.shape

(3, 1)

In [9]:
post_point=np.array(T).dot(initial_point)

In [10]:
post_point

array([[1.],
       [2.],
       [1.]])

In [11]:
from numpy.linalg import inv
inv(np.array(T)).dot(post_point)

array([[-4.44089210e-16],
       [ 8.32667268e-17],
       [ 1.00000000e+00]])

SO和transl2 仅旋转和仅平移

In [12]:
T=SO2(np.pi/3)

In [13]:
T

   0.5      -0.866     
   0.866     0.5       


In [14]:
from spatialmath.base import *
T=SE2.Tx(2)
T

   1         0         2         
   0         1         0         
   0         0         1         


In [15]:
from spatialmath.base import *
T=SE2.Ty(2)
T

   1         0         0         
   0         1         2         
   0         0         1         


In [16]:
from spatialmath.base import *
T=transl2([1,2])

In [17]:
T

array([[1., 0., 1.],
       [0., 1., 2.],
       [0., 0., 1.]])

3维变换

In [18]:
T=SE3.Rx(np.pi/3)
T

   1         0         0         0         
   0         0.5      -0.866     0         
   0         0.866     0.5       0         
   0         0         0         1         


In [19]:
T=rotx(np.pi/3)
T

array([[ 1.       ,  0.       ,  0.       ],
       [ 0.       ,  0.5      , -0.8660254],
       [ 0.       ,  0.8660254,  0.5      ]])

In [20]:
T=SE3.Ry(np.pi/2)
T

   0         0         1         0         
   0         1         0         0         
  -1         0         0         0         
   0         0         0         1         


In [21]:
T=SE3.Rx(np.pi)
T

   1         0         0         0         
   0        -1         0         0         
   0         0        -1         0         
   0         0         0         1         


In [22]:
T.plot()

In [23]:
T=np.array(T)
T[2][3]=0.02


In [24]:
T@(np.array([0,0,0,1]).reshape(4,1))

array([[0.  ],
       [0.  ],
       [0.02],
       [1.  ]])

In [25]:
T1=SE3.Rx(np.pi/2,t=np.array([0.1,0,0]))
T1
T2=SE3.Ry(np.pi/2,t=np.array([0,0.1,0]))
T2
T3=SE3.Rz(np.pi/2,t=np.array([0,0,0.1]))
T3

   0        -1         0         0         
   1         0         0         0         
   0         0         1         0.1       
   0         0         0         1         


In [26]:
#3个叠加，注意是按固定坐标轴旋转，左乘
T=T3*T2*T1
T

   0         0         1        -0.1       
   0         1         0         0         
  -1         0         0         0         
   0         0         0         1         


In [27]:
T.plot()

In [28]:
X = T1
X.animate(frame='A', color='green')
X.animate(start=None)

d:\robot\venv\lib\site-packages\matplotlib\animation.py:884: UserWarning: Animation was deleted without rendering anything. This is most likely not intended. To prevent deletion, assign the Animation to a variable, e.g. `anim`, that exists until you output the Animation using `plt.show()` or `anim.save()`.
  warnings.warn(


In [29]:
X = T2*T1
X.animate(frame='A', color='green')
X.animate(start=None)


In [30]:
X = T1*T2
X.animate(frame='A', color='green')
X.animate(start=None)


In [31]:
X = T3*T2*T1
X.animate(frame='A', color='green')
X.animate(start=None)

In [32]:
T

   0         0         1        -0.1       
   0         1         0         0         
  -1         0         0         0         
   0         0         0         1         


In [33]:
from spatialmath.base import animate
anim = animate.Animate(dims=[-1,1,-1,1]) # set up the 3D axes
anim.trplot(np.array(T), frame='A', color='green')  # draw the frame
anim.run(loop=True)  # animate it

In [34]:
SO3,rotx

(spatialmath.pose3d.SO3,
 <function spatialmath.base.transforms3d.rotx(theta: float, unit: str = 'rad') -> numpy.ndarray[typing.Tuple[typing.Literal[3], typing.Literal[3]], numpy.dtype[numpy.floating]]>)