In [1]:
%matplotlib tk


In [2]:
from roboticstoolbox import *
from spatialmath import *
from math import pi
import numpy as np

In [3]:
#标准DH

In [6]:
DFbot = DHRobot(
    [
                    RevoluteDH(alpha=np.pi/2,qlim=np.array([-np.pi,np.pi])),
                    RevoluteDH(a=0.15,qlim=np.array([-np.pi,np.pi])),
                    RevoluteDH(a=0.15,qlim=np.array([-np.pi,np.pi])),
                    RevoluteDH(d=-0.05494,alpha=np.pi/2,offset=np.pi/2,qlim=np.array([-np.pi,np.pi])),
                    RevoluteDH(d=0.068,alpha=-np.pi/2,qlim=np.array([-np.pi,3/2*np.pi])),  
                    RevoluteDH(d=0.033,qlim=np.array([-np.pi,3/2*np.pi]))

 
    ],
    name="DFbot",
)

In [4]:
DFbot

DHRobot: DFbot, 6 joints (RRRRRR), dynamics, standard DH parameters
┌───────────┬──────────┬──────┬────────┬─────────┬────────┐
│    θⱼ     │    dⱼ    │  aⱼ  │   ⍺ⱼ   │   q⁻    │   q⁺   │
├───────────┼──────────┼──────┼────────┼─────────┼────────┤
│  q1       │        0 │    0 │  90.0° │ -180.0° │ 180.0° │
│  q2       │        0 │ 0.15 │   0.0° │ -180.0° │ 180.0° │
│  q3       │        0 │ 0.15 │   0.0° │ -180.0° │ 180.0° │
│  q4 + 90° │ -0.05494 │    0 │  90.0° │ -180.0° │ 180.0° │
│  q5       │    0.068 │    0 │ -90.0° │ -180.0° │ 270.0° │
│  q6       │    0.033 │    0 │   0.0° │ -180.0° │ 270.0° │
└───────────┴──────────┴──────┴────────┴─────────┴────────┘

┌──┬──┐
└──┴──┘

In [5]:
DFbot.plot([0,-np.pi/2,0,0,0,0])

PyPlot3D backend, t = 0.05, scene:
  robot: Text(0.0, 0.0, 'DFbot')

In [ ]:
T1=DFbot.fkine([0,0,0,0,0,0])
T1

   1         0         0        -0.1657    
   0         1         0         0         
   0         0         1         0.1515    
   0         0         0         1         


In [9]:
help(DFbot.plot)

Help on method plot in module roboticstoolbox.robot.BaseRobot:

plot(q: Union[numpy.ndarray, List[float], Tuple[float], Set[float]], backend: Optional[Literal['swift', 'pyplot', 'pyplot2']] = None, block: bool = False, dt: float = 0.05, limits: Union[numpy.ndarray, List[float], Tuple[float], Set[float], NoneType] = None, vellipse: bool = False, fellipse: bool = False, fig: Optional[str] = None, movie: Optional[str] = None, loop: bool = False, **kwargs) -> Union[swift.Swift.Swift, roboticstoolbox.backends.PyPlot.PyPlot.PyPlot, roboticstoolbox.backends.PyPlot.PyPlot2.PyPlot2] method of roboticstoolbox.robot.DHRobot.DHRobot instance
    Graphical display and animation
    
    ``robot.plot(q, 'pyplot')`` displays a graphical view of a robot
    based on the kinematic model and the joint configuration ``q``.
    This is a stick figure polyline which joins the origins of the
    link coordinate frames. The plot will autoscale with an aspect
    ratio of 1.
    
    If ``q`` (m,n) representi

In [ ]:
#改进DH,有兴趣的同学可以自己尝试一下，看看改进DH和标准DH的区别在哪里

In [7]:
DFbot.plot([0,0,0,0,0,0], block=False)

PyPlot3D backend, t = 0.05, scene:
  robot: Text(0.0, 0.0, 'DFbot')

In [13]:
DFbot.plot([0,-np.pi/3,np.pi/6,np.pi,0], block=False)

PyPlot3D backend, t = 0.05, scene:
  robot: Text(0.0, 0.0, 'DFbot')

In [14]:
#正运动学

In [15]:
state0=[0,0,0,0,0]
T0=DFbot.fkine(state0)
state1=[0,-np.pi/6,0,np.pi/6,0]
T1=DFbot.fkine(state1)

In [16]:
#逆运动学

In [17]:
#Levemberg-Marquadt优化求解

In [18]:
sol = DFbot.ikine_LM(T1,q0=[0,np.pi/6,0,0,0],ilimit=100, slimit=100,joint_limits=True)

In [19]:
sol

IKSolution(q=array([ 0.        , -0.48857351, -0.07004978,  0.55862339,  0.        ]), success=True, iterations=5, searches=1, residual=8.161927300468807e-08, reason='Success')

In [20]:
sol.q

array([ 0.        , -0.48857351, -0.07004978,  0.55862339,  0.        ])

In [21]:
#Gauss-Newton优化求解

In [22]:
sol=DFbot.ikine_GN(T1,q0=[0,0,0,0,0],ilimit=1000, slimit=1000,joint_limits=True)

In [23]:
sol

IKSolution(q=array([ 1.96238062,  1.04734254,  0.2433365 , -2.30714312,  2.93825139]), success=False, iterations=1000, searches=1000, residual=0.0, reason='iteration and search limit reached, 1000 numpy.LinAlgError encountered')

In [24]:
sol.q

array([ 1.96238062,  1.04734254,  0.2433365 , -2.30714312,  2.93825139])

In [25]:
#Newton-Raphson优化求解

In [26]:
sol=DFbot.ikine_NR(T1,q0=[0,0,0,0,0],ilimit=1000, slimit=1000,joint_limits=True)

In [27]:
sol

IKSolution(q=array([-0.39688697, -0.0897743 , -0.72217098, -0.66859004, -0.08469746]), success=False, iterations=1000, searches=1000, residual=0.0, reason='iteration and search limit reached, 1000 numpy.LinAlgError encountered')

In [28]:
sol.q

array([-0.39688697, -0.0897743 , -0.72217098, -0.66859004, -0.08469746])

In [ ]:
#quadprog优化求解

In [ ]:
sol=DFbot.ikine_QP(T1,q0=[0,0,0,0,0],ilimit=100, slimit=100,joint_limits=True)